export const enum Tag {
	"Animate" = "Animate",
	"ConveyorBelt" = "ConveyorBelt",
	"Dropper" = "Dropper",
	"Float" = "Float",
	"Friend" = "Friend",
	"GamepassPrompt" = "GamepassPrompt",
	"Item" = "Item",
	"Lot" = "Lot",
	"LotSign" = "LotSign",
	"Pet" = "Pet",
	"PlayerHead" = "PlayerHead",
	"PurchaseButton" = "PurchaseButton",
	"Rainbow" = "Rainbow",
	"RebirthButton" = "RebirthButton",
	"RebirthUpgrade" = "RebirthUpgrade",
	"RebirthUpgradeAnimation" = "RebirthUpgradeAnimation",
	"Remover" = "Remover",
	"RespawnPlayer" = "RespawnPlayer",
	"SlidingDoor" = "SlidingDoor",
	"Spinner" = "Spinner",
	"Teleport" = "Teleport",
	"TimerButton" = "TimerButton",
	"Upgrader" = "Upgrader",
}
